spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
planner:
  email-service-endpoint: http://localhost:8088
  company-service-endpoint: http://localhost:8082
  bot-service-endpoint: http://localhost:8087
management:
  endpoints:
    web:
      exposure:
        include: "*"
