# application.yml

spring:
  profiles:
    active: dev
  application:
    name: faraday-service

server:
  error:
    whitelabel:
      enabled: false

planner:
  common:
    sentry-dsn: https://b3230c38171d485a8e96ac0039b9e467@o405363.ingest.sentry.io/5270833
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}

