server:
  port: 80


faraday:
  enable_programmatic_mapping: false
  tracing:
    enabled: false
  mappings:
    -
      name: faraday_route
      host: faraday.planner-v2.local
      destinations: httpbin.org
    -
      name: account_route
      host: account.planner-v2.local
      destinations: localhost:8081
    -
      name: company_route
      host: company.planner-v2.local
      destinations: localhost:8082
    -
      name: ical_route
      host: ical.planner-v2.local
      destinations: localhost:8083
    -
      name: whoami_route
      host: whoami.planner-v2.local
      destinations: localhost:8084
      timeout:
        connect: 10000
        read: 10000
    -
      name: superpowers_route
      host: superpowers.planner-v2.local
      destinations: localhost:8085
    -
      name: www_route
      host: www.planner-v2.local
      destinations: localhost:8086
    -
      name: myaccount_route
      host: myaccount.planner-v2.local
      destinations: localhost:9000
    -
      name: app_route
      host: app.planner-v2.local
      destinations: localhost:9001
management:
  endpoints:
    web:
      exposure:
        include: "*"
