spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082

planner:
  email-service-endpoint: http://localhost:8088
  account-service-endpoint: http://localhost:8081
  bot-service-endpoint: http://localhost:8087

management:
  endpoints:
    web:
      exposure:
        include: "*"