# application.yml

spring:
  profiles:
    active: dev
  application:
    name: www-service

server:
  error:
    whitelabel:
      enabled: false

planner:
  common:
    sentry-dsn: https://b3230c38171d485a8e96ac0039b9e467@o405363.ingest.sentry.io/5270833
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
  email-service-endpoint: ${EMAIL_SERVICE_ENDPOINT:http://email-service:8080}
  company-service-endpoint: ${COMPANY_SERVICE_ENDPOINT:http://company-service:8080}
  account-service-endpoint: ${ACCOUNT_SERVICE_ENDPOINT:http://account-service:8080}
  recaptcha-public: ${RECAPTCHA_PUBLIC}
  recaptcha-private: ${RECAPTCHA_PRIVATE}